require "import"
import "util.m3-import"
import "util.color"
import "MainConfig"
return{
  CoordinatorLayout,
  layout_width=-1,

  layout_height=-1,
  {
    AppBarLayout,
    layout_width=-1,
    backgroundColor=0,
    id="appBar",
    transitionName="appBar",
    {
      CollapsingToolbarLayout,
      layout_width=-1,
      layout_height="120dp",
      layout_scrollFlags=3,
      contentScrim=ColorDrawable(0),
      title="about",
      {
        MaterialToolbar,
        id="toolbar",
        layout_width=-1,
        layout_height="60dp",
        layout_collapseMode="pin",
      }
    },
  },
  {NestedScrollView,
    id="ns",
    layout_width="fill",
    layout_height="fill",
    layout_behavior="@string/appbar_scrolling_view_behavior",
    fillViewport="true",
    {LinearLayout,
      layout_width="fill",
      layout_height="fill",
      Orientation=1,

      {
        MaterialCardView;
        layout_width="fill";
        id="card1",
        StrokeColor=0,
        layout_marginLeft="10dp";
        layout_marginTop="10dp";
        layout_marginRight="10dp";
        {
          ImageView;
          layout_width="fill";
          layout_height="200dp";
          src="res/img3.jpg";
          scaleType="centerCrop";
        };
        {
          LinearLayout;
          gravity="center";
          orientation="vertical";
          layout_width="fill";
          layout_gravity="center";
          {
            MaterialTextView;
            text="LingRain-Android";
            textColor="#ffffff",
            textSize="25sp";
            id="maintitle",
          };
          {
            MaterialTextView;
            text="2024 Winter";
            id="maintitle2",
            textColor="#ffffff",
            gravity="center";
          };
        };
      };
      {
        TextView;
        text="关于应用";
        layout_marginTop="20dp",
        layout_marginLeft="20dp",
      },
      {
        LinearLayout;
        w=-1;
        {
          RecyclerView,
          layout_width="fill";
          layout_height="fill",
          id="rec1",
        },
      };
      {
        TextView;
        text="贡献者(LingRain旗下所有应用)";
        layout_marginTop="5dp",
        layout_marginLeft="20dp",
      },
      {
        RecyclerView,
        layout_width="fill";
        layout_height="fill",
        id="rec2",
      },
      {
        Space;
        w=-1,
        h="128dp",
      }
    };

  };
};