import "util.m3-import"
import "util.color"
import "MainConfig"
return{
  CoordinatorLayout,
  layout_width=-1,
  layout_height=-1,
  {
    AppBarLayout,
    backgroundColor=0,
    layout_width=-1,
    id="appBar",
        transitionName="appBar",
    {
      CollapsingToolbarLayout,
      layout_width=-1,
      layout_height="120dp",
      layout_scrollFlags=3,
      
      contentScrim=ColorDrawable(0),
      title="LingRain",
      {
        MaterialToolbar,
        id="toolbar",
        layout_width=-1,
        layout_height="60dp",
        --layout_collapseMode="pin",
      },
    },
  },
  {NestedScrollView,
    id="ns",
    layout_width="fill",
    layout_height="fill",
    layout_behavior="@string/appbar_scrolling_view_behavior",
    fillViewport="true",
    {LinearLayout,
      layout_width="fill",
      layout_height="fill",
      Orientation=1,
      padding="10dp";
      {
        MaterialCardView;
        layout_width="match_parent";
        layout_height="180dp";
        radius="15dp";
        --StrokeColor=colorPrimary,
        cardElevation="0",
        StrokeColor=0,
        {
          ImageView;
          layout_width="fill";
          layout_height="fill";
          src="res/img1.jpg";
          scaleType="centerCrop";
        };
      };
      {
        MaterialCardView;
        layout_width="match_parent";
        layout_marginTop="10dp";
        id="userdata";
        --StrokeColor=colorPrimaryContainer,
        {
          LinearLayout;
          layout_width="match_parent";
          padding="15dp";
          layout_height="wrap_content";
          {
            LinearLayout;
            layout_height="wrap_content";
            layout_width="match_parent";
            gravity="center";
            {
              FrameLayout;
              layout_height="50dp";
              layout_width="50dp";
              {
                MaterialCardView;
                layout_width="50dp";
                radius="80";
                layout_height="50dp";
                StrokeColor=0,
                {
                  ImageView;
                  layout_width="match_parent";
                  layout_gravity="center";
                  layout_height="match_parent";
                  id="head";
                  src="res/head.jpg",
                  scaleType="centerCrop";
                };

              };
              --[==[{
                ImageView;
                layout_height="20dp";
                layout_width="20dp";
                ColorFilter=colorOnBackground,
                layout_gravity="bottom|right";
                src="res/camera.png",
              };
            ]==]
            };
            {
              LinearLayout;
              layout_height="wrap_content";
              layout_width="match_parent";
              orientation="vertical";
              layout_marginLeft="10dp";
              layout_marginRight="10dp";
              {
                TextView;
                TextSize="10sp";
                id="name";
                TextColor=colorOnBackground;
                text="游客账号";
              };
              {
                TextView;
                TextSize="5sp";
                TextColor=colorOnBackground;
                id="h_time";
                text="time";
              };
            };
          };
        };
      };
      {
        MaterialCardView;
        layout_width="match_parent";
        layout_height="wrap_content";
        layout_marginTop="10dp",
        id="card",
        --StrokeColor=colorPrimaryContainer,
        {
          LinearLayout;
          layout_width="match_parent";
          layout_height="wrap_content";
          orientation="vertical";
          padding="15dp";
          {
            TextView;
            textSize="20sp";
            layout_marginTop="5dp";
            text="Time";
            id="time",
            TextColor=colorOnBackground;
          };
          {
            TextView;
            TextColor=colorOnBackground;
            text="放心出发吧";
          };
          {
            TextView;
            textSize="20sp";
            layout_marginTop="15dp";
            text="启程";
            TextColor=colorOnBackground;
          };
          {
            TextView;
            TextColor=colorOnBackground;
            text="启程，是人生旅途中的一次次勇敢跨越，它不仅代表着物理上的移动，更是心灵成长与自我发现的开始。每一次出发，都是一次与未知的邂逅，一次对自我极限的挑战。在启程的道路上，我们学会放下过往的包袱，拥抱变化，接受新知。它教会我们，真正的勇气不在于无畏地前行，而在于在未知的旅途中，依然能够坚持自己的方向，保持内心的宁静与坚定。启程，是生命之歌中最动听的旋律，它激励我们不断探索，不断超越，直至达到心灵的彼岸。";
          };
          {
            TextView;
            textSize="20sp";
            layout_marginTop="15dp";
            text="生命的意义";
            TextColor=colorOnBackground;
          };
          {
            TextView;
            TextColor=colorOnBackground;
            text="“生命所存在的意义不在于永恒，而在于每一刻的价值。”";
          };
          {
            TextView;
            TextColor=colorOnBackground;
            text="生命如同一朵花，绽放时绚烂夺目，凋零时却悄然无声。它短暂，却因短暂而珍贵；它脆弱，却因脆弱而美丽。每一片花瓣都承载着时光的痕迹，每一缕芬芳都诉说着存在的意义。我们追逐美好事物，或许正是因为它们像生命一样，短暂却耀眼，脆弱却动人。无论是朝阳初升时的光芒，还是暮色降临时的温柔，美好总在不经意间触动心弦，提醒我们：即使生命如花般短暂，也要尽情绽放，因为每一刻的灿烂，都是对时光最好的回应。";
          };
                  {
            TextView;
            textSize="20sp";
            layout_marginTop="15dp";
            text="LingRainX";
            TextColor=colorOnBackground;
          };
          {
            TextView;
            TextColor=colorOnBackground;
            text=[==[v1.0 @LingRain Studio
Made with LuaAppX & OpenLuaX+]==];
          };
        };
      };
      {View,
        layout_height="128dp",
      };
    };

  };
  {
    FloatingActionButton;
    layout_margin="16dp";
    src="res/add.png";
    layout_gravity="end|bottom";
    id="fab";
  };
};